### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Hitman477** [SkyCraft78/SuperGuilds-8.0#2]
Add new buildings, such as Tavern, Glory Hall, Watchtower, Wall and Gates as a category

**Comment by SkyCraft78** [comment]
Hey 👋
Could you please describe all buildings with their utilities?

**Comment by Hitman477** [comment]
Tavern: place to heal, take a food and short sleep.
Glory hall: place, contains NPC with player nickname, TOP - 10/15/20 killers of guild
Watchtower - decorative building.
Wall and gates - the template by which the guild land is enclosed, and gate to pass throught. Mostly decorative.

**Comment by SkyCraft78** [comment]
Okay, I'll try implement them after the war"s feature release!
Thanks for these ideas :)
